# Подготовка датасета

### Сначала соеденим все имеющиеся данные в 1 датасет

In [2]:
import pandas as pd
import numpy as np
from datetime import datetime
import time

In [3]:
df_clust = pd.read_csv('user_clusters-2.csv').drop(columns=['Unnamed: 0'])

In [4]:
df_clust.set_index('user_id', inplace = True)

In [5]:
df_clust.head()

,0,1,2,3,4,5,6,7,8,9,...,190,191,192,193,194,195,196,197,198,199
user_id,,,,,,,,,,,,,,,,,,,,,
13070801,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.00000,0.0,...,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0
21354225,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.00000,0.0,...,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0
30099458,0.0,0.009950,0.000000,0.004975,0.0,0.0,0.0,0.024876,0.00995,0.0,...,0.0,0.004975,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0
30179239,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.00000,0.0,...,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0
34075597,0.0,0.003704,0.003704,0.011111,0.0,0.0,0.0,0.000000,0.00000,0.0,...,0.0,0.003704,0.0,0.003704,0.0,0.0,0.0,0.007407,0.0,0.0

In [7]:
df_info = pd.read_csv('users_info.csv')

In [8]:
df_info.drop(columns=['sex', 'status', 'smoking', 'alcohol', 'parth_id', 'country', 'city'], inplace=True)

In [9]:
df_info.set_index('user_id', inplace = True)

In [11]:
df_info.head()

,bdate,flwrs,videos,audios,photos,friends,subs,pages,posts_n,pst_frq,wall_likes_mean,avatar_frq,avatar_mean
user_id,,,,,,,,,,,,,
490298034,4.3.2006,49,1103,1074,13,30,2,115,1,0.002829,28.000000,0.028886,72.538462
194510535,12.5.2003,121,225,724,107,53,1,295,13,0.105883,2.333333,0.056470,10.620000
514865204,12.11.2005,3,0,11,1,2,0,12,2,0.059495,1.000000,0.059495,1.000000
582801768,8.3.2000,0,4,1,7,28,0,7,5,0.120984,4.000000,0.030246,9.000000
580119484,9.8.2004,0,0,1,1,1,0,9,5,0.077432,0.500000,0.019358,1.000000

In [12]:
df_info['bdate'] = df_info['bdate'].apply(lambda bd: time.mktime(datetime.strptime(bd, "%d.%m.%Y").timetuple()))

In [13]:
df = df_info.merge(df_clust, on='user_id', how='inner')

In [14]:
df.head()

,bdate,flwrs,videos,audios,photos,friends,subs,pages,posts_n,pst_frq,...,190,191,192,193,194,195,196,197,198,199
user_id,,,,,,,,,,,,,,,,,,,,,
490298034,1.141420e+09,49,1103,1074,13,30,2,115,1,0.002829,...,0.0,0.006623,0.0,0.0,0.0,0.0,0.0,0.0,0.003311,0.0
194510535,1.052683e+09,121,225,724,107,53,1,295,13,0.105883,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
514865204,1.131743e+09,3,0,11,1,2,0,12,2,0.059495,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
582801768,9.524628e+08,0,4,1,7,28,0,7,5,0.120984,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.031250,0.0
455213471,1.061928e+09,25,189,62,32,147,10,48,157,0.777991,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0

In [15]:
df.to_csv('final_dataset.csv')

# Обучение моделей

## Для начала обучим модель линейной регрессии

In [123]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error as mse, r2_score, mean_absolute_error as mae
import pandas as pd
from joblib import dump

In [124]:
df = pd.read_csv('final_dataset.csv').set_index('user_id')

In [125]:
len(df)

23859

In [126]:
df.head()

,bdate,flwrs,videos,audios,photos,friends,subs,pages,posts_n,pst_frq,...,191,192,193,194,195,196,197,198,199,text_likes
user_id,,,,,,,,,,,,,,,,,,,,,
490298034,1.141420e+09,49,1103,1074,13,30,2,115,1,0.002829,...,0.006623,0.0,0.0,0.0,0.0,0.0,0.0,0.003311,0.0,302
194510535,1.052683e+09,121,225,724,107,53,1,295,13,0.105883,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,2
514865204,1.131743e+09,3,0,11,1,2,0,12,2,0.059495,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,1
582801768,9.524628e+08,0,4,1,7,28,0,7,5,0.120984,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.031250,0.0,32
455213471,1.061928e+09,25,189,62,32,147,10,48,157,0.777991,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,140

In [127]:
# Transform Y_test['bdate'] and Y_pred from timestamp to year
def timestamp_to_year(Y_pred, Y_test):
    for idx, y in enumerate(Y_pred):
        Y_pred[idx] = datetime.fromtimestamp(y).year
        Y_test[idx] = datetime.fromtimestamp(Y_test[idx]).year
    return Y_pred, Y_test

In [145]:
def MAE(Y_test, Y_pred):
    er=[]
    for i, test in enumerate(Y_test):
        a = abs(Y_pred[i] - test)
        er.append(a)

    print('MAE_test = {}'.format(sum(er)/len(er)))
    print('Top 10 outliers: {}'.format(sorted(er, reverse=True)[:10]))
    
    return er

In [140]:
def train(df, regr, train_perc=20):
    
    n_test = int(len(df)*train_perc/100)

    Y_test = df['bdate'][-n_test:].to_numpy()
    Y_train = df['bdate'][:-n_test]

    print('Train size: {}'.format(len(Y_train)))
    print('Test size: {}'.format(len(Y_test)))
    
    df.drop(columns=['bdate', 'text_likes'], inplace = True)

    X_test = df[-n_test:]
    X_train = df[:-n_test]

    regr.fit(X_train, Y_train)
    print('R2_train = {}'.format('%.3f'%regr.score(X_train, Y_train)))
    print('R2_test = {}'.format('%.3f'%regr.score(X_test, Y_test)))

    Y_pred = regr.predict(X_test)

    Y_pred, Y_test = timestamp_to_year(Y_pred, Y_test)
    
    error = MAE(Y_test, Y_pred)
    print('MSE = {}'.format('%.3f'%mse(Y_test, Y_pred, squared= False)))
    
    return X_test, Y_test, Y_pred, error, regr

Ошибка +- 5 лет. 

- Для уменьшения ошибки, можно попробовать избавиться от юзеров-халявщиков, которые могли указать неверные данные

- Включать в датасет только пользователей, для которых нашлось 100+ лайков и репостов

- Предсказывать не год рождения, а точную дату. Некоторые родились в последний день года

- Также можно прогнать ту же линейную регрессию через разные варианты кластеров в цикле. Оставить на ночь

1 из самых предиктивный признаков - кластер про отпуск (№196)

### Фильтр данных

In [35]:
df_init = pd.read_csv('final_dataset.csv').set_index('user_id')

Выбери 1 из 6 следующих строк:

In [79]:
# Со всем - без фильтра:
df2 = df_init.copy()

In [261]:
# Со всем + фильтр:
df2 = df_init.loc[(df_init['text_likes'] > 100) & (df_init['text_likes'] < 600)].copy()

In [162]:
# Без кластеров и без фильтра:
df2 = df_init.loc[:, 'bdate':'avatar_frq'].copy()
df2['text_likes'] = df_init['text_likes']

In [563]:
# Только кластеры, без фильтра:
df2 = df_init.loc[:,'0':'199']
df2['bdate'] = df_init['bdate']
df2['text_likes'] = df_init['text_likes']

In [50]:
# Только кластеры, с фильтром:
df2 = df_init.loc[:,'0':'199']
df2['bdate'] = df_init['bdate']
df2['text_likes'] = df_init['text_likes']
df2 = df2.loc[(df_init['text_likes'] > 100)]

In [52]:
# Без кластеров (инфа со страницы), с фильтром:
df2 = df_init.loc[:, 'bdate':'avatar_frq'].copy()
df2['text_likes'] = df_init['text_likes']
df2 = df2.loc[(df_init['text_likes'] > 100)]

In [262]:
len(df2)

7384

In [263]:
regr = LinearRegression()
X_test, Y_test, Y_pred, error, model= train(df2, regr)

Train size: 5908
Test size: 1476
R2_train = 0.434
R2_test = 0.322
MAE_test = 4.543360433604336
Top 10 outliers: [31.0, 24.0, 23.0, 19.0, 18.0, 18.0, 17.0, 17.0, 17.0, 17.0]
MSE = 5.747

#### Supervise a model on the whole set

to increase perfomance on new data

In [177]:
from joblib import dump
regr = LinearRegression()
X_test, Y_test, Y_pred, error, model= train(df2, regr, 1)
dump(regr, 'Regression/linear.joblib')

Train size: 7311
Test size: 73
R2_train = 0.430
R2_test = 0.475
MAE_test = 3.506849315068493
Top 10 outliers: [10.0, 9.0, 9.0, 8.0, 8.0, 8.0, 7.0, 7.0, 7.0, 7.0]
MSE = 4.246

['Regression/linear.joblib']

### Необъективность оценок
При более строгом фильтре R2 становится значительно выше, но MSE падает (примерно на 1 год, что не критично). Я думаю, R2 также повязан на размере выборке, значит, необходимо сделать текстовую выборку фиксированной, и уже потом проводить на ней эксперименты. 

### Эксперименты с одной длиной сета (объективные по отдельности):
#### - Без фильтра:
Со всем:

 - Train size: 19088; Test size: 4771

 - R2_train = 0.226; R2_test = 0.156; MAE_test = 5.167

####  - Фильтр: text_likes > 100
 - Мы можем себе позволить именно такой фильтр. N = 5507

Только с кластерами: R2 = 0.415; MAE: 4.303

Без кластеров, только данные со страницы: R2 = 0.0813; MAE: 3.886

Со всем: 

Train size: 6059; Test size: 1514

R2_train = 0.435; R2_test = 0.320; MAE_test = 4.599

### Теперь попробуем выделить выбросы
Для этого можно обучить ещё одну модель на пользователях с крупной ошибкой, но сначала посмотрим на этих пользователей своими глазами

In [77]:
X_test['error'] = error
X_test['year_pred'] = Y_pred
X_test['year_real'] = Y_test

/home/koks/Documents/Programming/Python/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/home/koks/Documents/Programming/Python/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/home/koks/Documents/Programming/Python/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [78]:
X_test.sort_values('error', ascending = False)

,flwrs,videos,audios,photos,friends,subs,pages,posts_n,pst_frq,wall_likes_mean,...,193,194,195,196,197,198,199,error,year_pred,year_real
user_id,,,,,,,,,,,,,,,,,,,,,
139053157,118,404,579,341,323,3,140,300,0.410437,3.153846,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,29.0,2011.0,1982.0
392707756,39,0,2,31,209,3,44,300,0.559273,1.564189,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,23.0,2009.0,1986.0
94806756,594,9,0,757,850,4,1645,300,0.311562,34.858586,...,0.006211,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,23.0,2000.0,1977.0
2957022,383,1279,353,538,559,9,1822,300,0.331895,3.256849,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,19.0,1995.0,1976.0
5645366,178,122,191,1278,3832,211,163,208,0.143029,3.097561,...,0.000000,0.000000,0.000000,0.005650,0.000000,0.005650,0.000000,18.0,1994.0,1976.0
331680108,4,49,354,252,62,13,44,277,0.244118,0.482759,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,17.0,1987.0,2004.0
235961512,164,4,0,498,67,0,203,299,0.257764,13.213793,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,17.0,1986.0,2003.0
301941436,0,3,167,1899,96,1,124,300,0.579080,3.578397,...,0.018072,0.000000,0.000000,0.000000,0.012048,0.000000,0.000000,16.0,1987.0,2003.0
175657390,152,103,0,211,174,0,150,300,0.268643,4.742268,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,16.0,1981.0,1997.0
547853800,0,0,126,33,104,57,18,70,1.018464,3.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,16.0,1989.0,2005.0
360995947,87,10,0,269,140,3,204,273,0.330298,1.217213,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,16.0,1985.0,2001.0
250470579,84,67,261,1270,65,0,39,299,0.808843,2.802676,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,16.0,1973.0,1989.0
29645357,183,59,301,597,47,0,1077,300,0.585697,0.716667,...,0.009091,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.0,1992.0,1978.0
134777030,224,307,0,11,74,1,239,300,0.016088,0.856164,...,0.015038,0.000000,0.000000,0.000000,0.000000,0.007519,0.000000,14.0,1987.0,2001.0
239328067,88,4,0,10,88,0,110,300,0.352170,1.117450,...,0.025210,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.0,1988.0,2002.0
284578719,58,4,144,111,180,3,16,181,0.129249,3.558011,...,0.000000,0.000000,0.000000,0.004484,0.000000,0.000000,0.000000,14.0,1976.0,1990.0
426658158,157,137,0,113,1132,16,257,293,0.349391,9.445283,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.0,1988.0,2002.0
332120041,209,2,0,10,96,0,164,244,0.197982,0.924686,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.0,1989.0,2003.0
218637828,46,16,4,474,73,4,13,142,0.114212,6.125984,...,0.000000,0.000000,0.000000,0.000000,0.008547,0.025641,0.000000,13.0,1975.0,1988.0
82350466,245,607,0,1168,216,1,235,127,0.092862,7.350000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.0,1993.0,1980.0
287754623,34,1,115,50,54,1,5,300,0.313509,0.323333,...,0.000000,0.000000,0.000000,0.013699,0.000000,0.018265,0.000000,13.0,1975.0,1988.0
411546658,64,62,0,24,240,14,206,140,0.165453,2.873134,...,0.000000,0.006993,0.000000,0.000000,0.000000,0.000000,0.000000,13.0,1991.0,2004.0
324225147,82,46,0,38,199,0,2778,160,0.137013,5.044025,...,0.000000,0.000000,0.000000,0.003937,0.000000,0.000000,0.000000,13.0,2015.0,2002.0
229180812,474,73,0,131,150,0,63,299,0.319249,3.326087,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.0,1990.0,2003.0
250470579,84,67,261,1270,65,0,39,299,0.808843,2.802676,...,0.000000,0.000000,0.000000,0.000000,0.062500,0.000000,0.000000,13.0,1976.0,1989.0
266011894,13,17,0,111,20,0,19,275,0.226341,0.937269,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.0,1989.0,2002.0
277560755,33,151,0,310,136,2,123,112,0.204077,2.032258,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.0,1990.0,2003.0
212877109,117,16,115,621,153,2,87,300,0.680645,2.135135,...,0.000000,0.000000,0.000000,0.000000,0.005051,0.000000,0.000000,13.0,1972.0,1985.0
552509856,141,2,0,11,592,1,38,5,0.121771,227.500000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.0,1991.0,2004.0
419019254,74,18,539,82,341,0,32,6,0.007726,30.166667,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.0,1982.0,1995.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238708064,302,6,138,13,134,12,45,64,0.159012,0.063492,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,1990.0,1990.0
145118663,314,2,0,31,222,0,27,15,0.008667,13.181818,...,0.004854,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,1994.0,1994.0
28792570,188,59,78,36,182,0,52,300,0.342378,0.466667,...,0.000000,0.000000,0.000000,0.000000,0.003623,0.010870,0.000000,0.0,1984.0,1984.0
279609065,290,131,605,824,119,1,169,300,1.377599,0.533557,...,0.004425,0.000000,0.000000,0.000000,0.000000,0.004425,0.000000,0.0,1991.0,1991.0
169062695,157,16,871,52,104,0,38,300,0.307260,0.779310,...,0.008130,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,1993.0,1993.0
141673133,76,4,27,25,34,1,46,121,0.083510,0.567797,...,0.003788,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,1982.0,1982.0
159288896,370,261,982,4220,319,9,134,299,0.360481,5.737931,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.018868,0.000000,0.0,1985.0,1985.0
298115719,61,4,124,188,169,0,18,169,0.132056,4.183544,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.006623,0.000000,0.0,1987.0,1987.0
210906001,222,43,2258,625,519,15,111,232,0.160353,12.130045,...,0.005051,0.000000,0.000000,0.000000,0.000000,0.005051,0.000000,0.0,1993.0,1993.0
203138019,1669,0,289,75,2919,953,42,300,1.001367,17.739865,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,1990.0,1990.0
214566605,222,1,0,24,209,0,27,120,0.082578,13.697479,...,0.000000,0.000000,0.000000,0.000000,0.003367,0.000000,0.000000,0.0,1987.0,1987.0
103686760,48,3,27,1054,389,1,8,202,0.149148,13.211055,...,0.000000,0.000000,0.000000,0.008163,0.000000,0.000000,0.000000,0.0,1982.0,1982.0
321187837,59,1,39,14,181,1,170,180,0.127358,0.621469,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,1991.0,1991.0
139824417,101,4,495,63,209,4,70,174,0.122879,1.766467,...,0.007519,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,1983.0,1983.0
167964980,143,8,78,265,462,1,35,299,0.298792,6.807432,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,1986.0,1986.0
261180310,142,44,155,123,152,9,44,300,0.208797,4.391892,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,1992.0,1992.0
247631273,123,11,79,83,239,4,113,240,0.163802,1.344828,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,1989.0,1989.0
7778511,198,72,72,274,101,1,27,147,0.105806,2.071942,...,0.000000,0.000000,0.000000,0.007463,0.000000,0.000000,0.000000,0.0,1982.0,1982.0
184770596,408,32,1045,1121,336,1,545,299,0.461623,19.052045,...,0.005952,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,1995.0,1995.0
87787255,813,762,2788,224,1098,0,342,300,0.217738,23.786441,...,0.000000,0.000000,0.000000,0.005000,0.000000,0.010000,0.000000,0.0,1996.0,1996.0
272865231,50,18,803,44,156,0,18,170,0.132325,3.385542,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,1991.0,1991.0
149418128,48,5,0,3,63,1,38,300,0.595084,0.107023,...,0.007491,0.000000,0.000000,0.000000,0.018727,0.000000,0.000000,0.0,1983.0,1983.0
282789837,25,19,0,271,199,4,79,300,0.240454,0.557432,...,0.005988,0.000000,0.000000,0.005988,0.041916,0.005988,0.000000,0.0,1987.0,1987.0
68504992,164,3,7,630,299,1,53,300,0.468269,5.845638,...,0.000000,0.000000,0.000000,0.000000,0.010274,0.003425,0.000000,0.0,1987.0,1987.0
180204355,60,5,15,208,82,2,42,300,0.289155,0.418060,...,0.007353,0.000000,0.000000,0.000000,0.018382,0.000000,0.000000,0.0,1984.0,1984.0
43434919,1005,1720,0,802,621,112,822,300,0.273375,0.802239,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.005263,0.000000,0.0,1994.0,1994.0
40432770,67,230,0,27,129,1,74,171,0.117128,1.666667,...,0.006289,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,1981.0,1981.0
260004730,22,5,55,138,233,0,137,170,0.168674,1.546053,...,0.000000,0.000000,0.007143,0.000000,0.000000,0.000000,0.007143,0.0,1992.0,1992.0
188346115,94,2,0,302,159,1,9,165,0.119477,6.735099,...,0.000000,0.000000,0.000000,0.008696,0.000000,0.000000,0.000000,0.0,1987.0,1987.0
279113315,86,181,0,163,127,4,25,91,0.060615,8.195402,...,0.007605,0.000000,0.000000,0.000000,0.007605,0.003802,0.000000,0.0,1991.0,1991.0

In [44]:
X_test[X_test.user_id == 367415708]

AttributeError: 'DataFrame' object has no attribute 'user_id'

Ошибка на пользователе 195020820 аномально большая, но он - обычный юзер. Его самый любимый кластер - фильмы (№87)

In [244]:
model.coef_[13+87]

-7.296122027284393

Видно, что это мощный предиктор большого возраста.

У пользователя достаточно высокая частота появления постов (поэтому, он прошел фильтр), но эти посты с текстом на картинке, соответственно, полезной информации нашлось очень мало: почти только про фильмы.

Вывод: халявщики могут быть обычными людьми, а не фейками. Желание халявы - тоже предиктор. Проблема не в них, а в нелинейности исходных данных, недостатке информации о лайках, или в недостаточно информативной кластеризации.

Предлагаю:
    
1) Обучить нейронную сеть для нелинейного предсказаниия

2) Сделать фильтр по кол-ву лайков/постов с текстом, а не по всем вместе - помогло уменьшить ошибку почти на год

3) Сделать подбор параметров кластеризации

2) Имплементировать распознование текста с картинок

### Улучшаем фильтр

In [17]:
from dask import dataframe as dd

In [21]:
df_posts = dd.read_parquet('preprocesed-2.parquet')
df_posts = df_posts.dropna().drop(columns=['text'])

In [29]:
count = df_posts.groupby('user_id').count().compute()
count.columns=['text_likes']

merged = df.merge(count, on='user_id', how='inner')

In [30]:
merged.head()

,bdate,flwrs,videos,audios,photos,friends,subs,pages,posts_n,pst_frq,...,191,192,193,194,195,196,197,198,199,text_likes
user_id,,,,,,,,,,,,,,,,,,,,,
490298034,1.141420e+09,49,1103,1074,13,30,2,115,1,0.002829,...,0.006623,0.0,0.0,0.0,0.0,0.0,0.0,0.003311,0.0,302
194510535,1.052683e+09,121,225,724,107,53,1,295,13,0.105883,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,2
514865204,1.131743e+09,3,0,11,1,2,0,12,2,0.059495,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,1
582801768,9.524628e+08,0,4,1,7,28,0,7,5,0.120984,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.031250,0.0,32
455213471,1.061928e+09,25,189,62,32,147,10,48,157,0.777991,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,140

In [31]:
merged.to_csv('final_dataset.csv')

### Настройка кластеризации

Последний шаг - подбор параметров для алгоритма кластеризации в зависимости от ошибки линейной регрессии.

В нашем случае параметр 1 - количество кластеров

## Обучим нейронную сеть

Для начала попробуем 1 скрытый слой по 20 юнитов, либо сразу запустим подбор гиперпараметров

In [81]:
from sklearn.neural_network import MLPRegressor

In [82]:
df = pd.read_csv('final_dataset.csv').set_index('user_id')

In [118]:
df.head()

,bdate,flwrs,videos,audios,photos,friends,subs,pages,posts_n,pst_frq,...,191,192,193,194,195,196,197,198,199,text_likes
user_id,,,,,,,,,,,,,,,,,,,,,
490298034,1.141420e+09,49,1103,1074,13,30,2,115,1,0.002829,...,0.006623,0.0,0.0,0.0,0.0,0.0,0.0,0.003311,0.0,302
194510535,1.052683e+09,121,225,724,107,53,1,295,13,0.105883,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,2
514865204,1.131743e+09,3,0,11,1,2,0,12,2,0.059495,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,1
582801768,9.524628e+08,0,4,1,7,28,0,7,5,0.120984,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.031250,0.0,32
455213471,1.061928e+09,25,189,62,32,147,10,48,157,0.777991,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,140

In [254]:
df2 = df.loc[(df['text_likes'] > 0)].copy()

In [255]:
len(df2)

23859

In [256]:
regr = MLPRegressor(hidden_layer_sizes=(20,), max_iter=5000, activation = 'relu', solver='lbfgs', random_state=2)

In [257]:
X_test, Y_test, Y_pred, error, regr = train(df2, regr)

Train size: 19088
Test size: 4771
R2_train = 0.163
R2_test = -0.026
MAE_test = 5.388597778243555
Top 10 outliers: [182.0, 60.0, 43.0, 33.0, 31.0, 30.0, 26.0, 26.0, 25.0, 24.0]
MSE = 7.268

/home/koks/.local/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:471: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

Проблема в том, что алгоритм не сошелся, или в переобучении?
 - Выведи ошибку на тренеровочных данных

Если переобучение, попробуй регуляризацию

Если не алгоритм сходится, гугли, почему

if hidden_layer_sizes=(1,), It should perform as linear regression. if not, google, then ask

In [258]:
hidden_layer_sizes = [tuple([i,]) for i in range (1, 100, 2)]

In [260]:
param_grid = [
        {
            'activation' : ['relu', 'identity'],
            'solver' : ['lbfgs', 'sgd', 'adam'],
            'hidden_layer_sizes': hidden_layer_sizes
        }
       ]

Пробуем стандартизировать данные и разбираемся с выбросами: https://scikit-learn.org/stable/modules/preprocessing.html

Пробуем подбор параметров для нейронки

Потом можно попробовать нелинейную регрессию - kernel regression

Но сначала - презентация и кирпич